export const marketplaceABI = [
    {
      inputs: [
        { internalType: "address", name: "_tokenContract", type: "address" },
        { internalType: "address", name: "_salesContract", type: "address" },
      ],
      stateMutability: "nonpayable",
      type: "constructor",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: "uint256", name: "productId", type: "uint256" },
        { indexed: false, internalType: "string", name: "name", type: "string" },
        { indexed: false, internalType: "uint256", name: "price", type: "uint256" },
        { indexed: false, internalType: "address", name: "seller", type: "address" },
      ],
      name: "ProductAdded",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: "uint256", name: "productId", type: "uint256" },
        { indexed: true, internalType: "address", name: "buyer", type: "address" },
        { indexed: false, internalType: "uint256", name: "price", type: "uint256" },
        { indexed: false, internalType: "uint256", name: "saleId", type: "uint256" },
      ],
      name: "ProductPurchased",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: "uint256", name: "productId", type: "uint256" },
        { indexed: false, internalType: "string", name: "name", type: "string" },
        { indexed: false, internalType: "uint256", name: "price", type: "uint256" },
        { indexed: false, internalType: "bool", name: "active", type: "bool" },
      ],
      name: "ProductUpdated",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [{ indexed: false, internalType: "address", name: "newSalesContract", type: "address" }],
      name: "SalesContractUpdated",
      type: "event",
    },
    {
      inputs: [
        { internalType: "string", name: "_name", type: "string" },
        { internalType: "string", name: "_description", type: "string" },
        { internalType: "uint256", name: "_price", type: "uint256" },
      ],
      name: "addProduct",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      name: "getActiveProducts",
      outputs: [
        {
          components: [
            { internalType: "uint256", name: "id", type: "uint256" },
            { internalType: "string", name: "name", type: "string" },
            { internalType: "string", name: "description", type: "string" },
            { internalType: "uint256", name: "price", type: "uint256" },
            { internalType: "address", name: "seller", type: "address" },
            { internalType: "bool", name: "active", type: "bool" },
          ],
          internalType: "struct Marketplace.Product[]",
          name: "",
          type: "tuple[]",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "_productId", type: "uint256" }],
      name: "getProduct",
      outputs: [
        {
          components: [
            { internalType: "uint256", name: "id", type: "uint256" },
            { internalType: "string", name: "name", type: "string" },
            { internalType: "string", name: "description", type: "string" },
            { internalType: "uint256", name: "price", type: "uint256" },
            { internalType: "address", name: "seller", type: "address" },
            { internalType: "bool", name: "active", type: "bool" },
          ],
          internalType: "struct Marketplace.Product",
          name: "",
          type: "tuple",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "_seller", type: "address" }],
      name: "getProductsBySeller",
      outputs: [
        {
          components: [
            { internalType: "uint256", name: "id", type: "uint256" },
            { internalType: "string", name: "name", type: "string" },
            { internalType: "string", name: "description", type: "string" },
            { internalType: "uint256", name: "price", type: "uint256" },
            { internalType: "address", name: "seller", type: "address" },
            { internalType: "bool", name: "active", type: "bool" },
          ],
          internalType: "struct Marketplace.Product[]",
          name: "",
          type: "tuple[]",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "nextProductId",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "owner",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      name: "products",
      outputs: [
        { internalType: "uint256", name: "id", type: "uint256" },
        { internalType: "string", name: "name", type: "string" },
        { internalType: "string", name: "description", type: "string" },
        { internalType: "uint256", name: "price", type: "uint256" },
        { internalType: "address", name: "seller", type: "address" },
        { internalType: "bool", name: "active", type: "bool" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "_productId", type: "uint256" }],
      name: "purchaseProduct",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      name: "salesContract",
      outputs: [{ internalType: "contract SalesContract", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "_salesContract", type: "address" }],
      name: "setSalesContract",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      name: "tokenContract",
      outputs: [{ internalType: "contract IERC20", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_productId", type: "uint256" },
        { internalType: "string", name: "_name", type: "string" },
        { internalType: "string", name: "_description", type: "string" },
        { internalType: "uint256", name: "_price", type: "uint256" },
        { internalType: "bool", name: "_active", type: "bool" },
      ],
      name: "updateProduct",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
  ]